#!/bin/sh
set -e

echo "⏳ Installing dependencies..."
pnpm install --frozen-lockfile

echo ""
echo "⏳ Running linter..."
pnpm lint

echo ""
echo "⏳ Type checking..."
pnpm typecheck

echo ""
echo "⏳ Building..."
pnpm build

echo ""
echo "⏳ Running tests..."
pnpm test

echo ""
echo "✅ Pre-push checks passed"
